# Generated by Django 4.2.29 on 2026-04-01 04:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('extracted_text', models.TextField(blank=True)),
                ('resume_score', models.IntegerField(default=0)),
                ('detected_skills', models.TextField(blank=True)),
                ('detected_education', models.TextField(blank=True)),
                ('detected_experience', models.TextField(blank=True)),
                ('missing_skills', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('formatting_score', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
